theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "net"
device = "wlan0"
format = "{speed_up} {speed_down}"
interval = 2
use_bits = false

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %r"

[[block]]
block = "temperature"
interval = 3
collapsed = false
format = "{average}° {max}°"
chip = "coretemp-isa-0000"

[[block]]
block = "battery"
interval = 10
format = " {percentage}%"

[[block]]
block = "backlight"
